-- SPEC-BREADTOUR-001 — combined migrations (apply in Supabase Dashboard > SQL Editor)
-- Generated by concatenating supabase/migrations/*.sql in order.

-- ============================================================
-- 20260619000100_core_schema.sql
-- ============================================================
-- =============================================================================
-- SPEC-BREADTOUR-001 :: Migration 1 / Core schema
-- Tables: profiles, tours, tour_members, tour_invites
-- Plus SECURITY DEFINER membership helpers used by every RLS policy.
-- =============================================================================
-- Ordering note: this file MUST run before the spots/menus/stamps migration
-- (foreign keys reference tours) and before the RLS migration (policies call
-- the helper functions defined here).
-- All timestamps are server-side (now()): arrival/edit time source of truth is
-- the server, never the client device clock (SPEC A6 / NFR-CONFLICT-001).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
-- gen_random_uuid() ships with pgcrypto on managed Postgres / Supabase.
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
-- Wrapped in DO blocks so re-running the migration does not error on an
-- already-created type (idempotent-friendly per task constraint).
do $$ begin
  create type tour_member_role as enum ('owner', 'member');
exception when duplicate_object then null; end $$;

do $$ begin
  create type tour_invite_status as enum ('pending', 'accepted', 'rejected');
exception when duplicate_object then null; end $$;

do $$ begin
  create type spot_kind as enum ('bakery', 'restaurant');
exception when duplicate_object then null; end $$;

do $$ begin
  create type stamp_method as enum ('auto', 'manual');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- profiles : 1:1 with auth.users, holds display info the client may read.
-- (auth.users itself is not directly selectable by the anon/authenticated
-- roles, so a public-facing mirror is required to render member names.)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- tours : the stamp-rally itself. owner_id is the creator (REQ-F6-001).
-- ---------------------------------------------------------------------------
create table if not exists public.tours (
  id         uuid primary key default gen_random_uuid (),
  owner_id   uuid not null references auth.users (id) on delete cascade,
  name       text not null check (char_length(name) between 1 and 200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tours_owner_id_idx on public.tours (owner_id);

-- ---------------------------------------------------------------------------
-- tour_members : membership + role (REQ-F6-004/005). This table is the
-- authority for "who may see/edit a tour" and is referenced by every other
-- table's RLS policy via the helper functions below.
-- ---------------------------------------------------------------------------
create table if not exists public.tour_members (
  id        uuid primary key default gen_random_uuid (),
  tour_id   uuid not null references public.tours (id) on delete cascade,
  user_id   uuid not null references auth.users (id) on delete cascade,
  role      tour_member_role not null default 'member',
  joined_at timestamptz not null default now(),
  unique (tour_id, user_id)
);

create index if not exists tour_members_tour_id_idx on public.tour_members (tour_id);
create index if not exists tour_members_user_id_idx on public.tour_members (user_id);

-- ---------------------------------------------------------------------------
-- tour_invites : link/email invitations (REQ-F6-002/003).
-- token is for link-based invites; invited_email is optional for email invites.
-- ---------------------------------------------------------------------------
create table if not exists public.tour_invites (
  id            uuid primary key default gen_random_uuid (),
  tour_id       uuid not null references public.tours (id) on delete cascade,
  invited_email text,
  token         text not null unique default encode(gen_random_bytes(18), 'hex'),
  status        tour_invite_status not null default 'pending',
  invited_by    uuid not null references auth.users (id) on delete cascade,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists tour_invites_tour_id_idx on public.tour_invites (tour_id);
create index if not exists tour_invites_email_idx on public.tour_invites (invited_email);

-- ---------------------------------------------------------------------------
-- updated_at trigger : keeps updated_at = server now() on every UPDATE.
-- This is the server timestamp that row-level last-write-wins relies on
-- (NFR-CONFLICT-001/002 / D4). Clients never set updated_at.
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at ()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at ();

drop trigger if exists tours_set_updated_at on public.tours;
create trigger tours_set_updated_at
  before update on public.tours
  for each row execute function public.set_updated_at ();

drop trigger if exists tour_invites_set_updated_at on public.tour_invites;
create trigger tour_invites_set_updated_at
  before update on public.tour_invites
  for each row execute function public.set_updated_at ();

-- ---------------------------------------------------------------------------
-- Membership helper functions (SECURITY DEFINER).
--
-- These run with the function owner's privileges and therefore BYPASS RLS on
-- tour_members. That is required to avoid infinite recursion: tour_members'
-- own RLS policy needs to ask "is this user a member?", which would re-trigger
-- the same policy if it queried tour_members directly under RLS.
--
-- search_path is pinned to public to prevent search_path hijacking on a
-- SECURITY DEFINER function (a real privilege-escalation vector).
-- ---------------------------------------------------------------------------
create or replace function public.is_tour_member (p_tour_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.tour_members tm
    where tm.tour_id = p_tour_id
      and tm.user_id = auth.uid ()
  );
$$;

create or replace function public.is_tour_owner (p_tour_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.tour_members tm
    where tm.tour_id = p_tour_id
      and tm.user_id = auth.uid ()
      and tm.role = 'owner'
  );
$$;

-- ---------------------------------------------------------------------------
-- Auto-bootstrap : when a tour is created, insert the creator as the owner
-- member in the same transaction. Without this, the creator could not pass
-- their own RLS membership check and would be locked out of the tour they
-- just made (REQ-F6-001).
-- ---------------------------------------------------------------------------
create or replace function public.add_owner_membership ()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tour_members (tour_id, user_id, role)
  values (new.id, new.owner_id, 'owner')
  on conflict (tour_id, user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists tours_add_owner_membership on public.tours;
create trigger tours_add_owner_membership
  after insert on public.tours
  for each row execute function public.add_owner_membership ();

-- ---------------------------------------------------------------------------
-- Profile auto-provisioning : create a profiles row whenever a new auth user
-- signs up, so member lists can render a display name.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user ()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user ();


-- ============================================================
-- 20260619000200_spots_menus_stamps.sql
-- ============================================================
-- =============================================================================
-- SPEC-BREADTOUR-001 :: Migration 2 / Spots, menus, stamps
-- Tables: spots, spot_menus, stamps
-- Plus the atomic reorder_spots() function (REQ-F5-007 / D11).
-- =============================================================================
-- Depends on migration 1 (tours table + set_updated_at()).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- spots : a bakery/restaurant in the tour with coordinates + arrival radius.
--   - lat/lng : coordinates captured at registration (SPEC A8, REQ-F1-001).
--   - radius_m : arrival-detection radius, default 50m (SPEC A3, REQ-F1-001).
--   - order_index : planned visit order; kept gap-free by reorder_spots().
-- We do NOT store any raw coordinate stream here -- only the fixed spot
-- location. Member position history is never persisted (NFR-GEO-006 / A12).
-- ---------------------------------------------------------------------------
create table if not exists public.spots (
  id          uuid primary key default gen_random_uuid (),
  tour_id     uuid not null references public.tours (id) on delete cascade,
  name        text not null check (char_length(name) between 1 and 200),
  kind        spot_kind not null default 'bakery',
  lat         double precision not null check (lat between -90 and 90),
  lng         double precision not null check (lng between -180 and 180),
  radius_m    integer not null default 50 check (radius_m between 1 and 5000),
  order_index integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists spots_tour_id_idx on public.spots (tour_id);
-- Ordering reads ("show spots in visit order") hit (tour_id, order_index).
create index if not exists spots_tour_order_idx on public.spots (tour_id, order_index);

-- ---------------------------------------------------------------------------
-- spot_menus : member-entered signature/recommended menu items (F4).
--   - author_id : the member who entered this menu (REQ-F4-003 attribution).
--   - ON DELETE CASCADE from spots: deleting a spot removes its menus
--     (REQ-F6-007 / D3 / EC-09).
-- ---------------------------------------------------------------------------
create table if not exists public.spot_menus (
  id         uuid primary key default gen_random_uuid (),
  spot_id    uuid not null references public.spots (id) on delete cascade,
  author_id  uuid not null references auth.users (id) on delete cascade,
  menu_text  text not null check (char_length(menu_text) between 1 and 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists spot_menus_spot_id_idx on public.spot_menus (spot_id);

-- ---------------------------------------------------------------------------
-- stamps : a digital stamp earned by physically arriving at a spot (F1).
--   - tour_id is denormalized alongside spot_id so RLS membership checks and
--     realtime filters can run without an extra join. It is kept consistent
--     by an application-side / trigger guarantee (see sync trigger below).
--   - arrived_at : SERVER timestamp, the source of truth for arrival time
--     (SPEC A6, REQ-F1-003). Never set by the client.
--   - cancelled_at : soft-cancel marker. Cancellation sets this rather than
--     deleting the row, preserving history (REQ-F1-009 / D14).
--   - method : 'auto' (GPS) or 'manual' (peer-verified check-in, REQ-F1-007).
-- We store only arrived_at + spot/user identifiers -- no raw coordinates
-- (NFR-GEO-006 / A12).
-- ---------------------------------------------------------------------------
create table if not exists public.stamps (
  id           uuid primary key default gen_random_uuid (),
  spot_id      uuid not null references public.spots (id) on delete cascade,
  tour_id      uuid not null references public.tours (id) on delete cascade,
  user_id      uuid not null references auth.users (id) on delete cascade,
  method       stamp_method not null default 'auto',
  arrived_at   timestamptz not null default now(),
  cancelled_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists stamps_tour_id_idx on public.stamps (tour_id);
create index if not exists stamps_spot_id_idx on public.stamps (spot_id);
create index if not exists stamps_user_id_idx on public.stamps (user_id);

-- @MX:ANCHOR: [AUTO] Partial unique index enforces "one ACTIVE stamp per
-- (spot, user)" while allowing re-stamping after a cancel.
-- @MX:REASON: REQ-F1-004 forbids duplicate active stamps, but REQ-F1-011 / D14
-- require that a cancelled stamp (cancelled_at IS NOT NULL) does NOT block a
-- fresh stamp. A full UNIQUE(spot_id,user_id) would break re-stamping; the
-- WHERE cancelled_at IS NULL predicate is the invariant that satisfies both.
create unique index if not exists stamps_active_unique
  on public.stamps (spot_id, user_id)
  where cancelled_at is null;

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
drop trigger if exists spots_set_updated_at on public.spots;
create trigger spots_set_updated_at
  before update on public.spots
  for each row execute function public.set_updated_at ();

drop trigger if exists spot_menus_set_updated_at on public.spot_menus;
create trigger spot_menus_set_updated_at
  before update on public.spot_menus
  for each row execute function public.set_updated_at ();

drop trigger if exists stamps_set_updated_at on public.stamps;
create trigger stamps_set_updated_at
  before update on public.stamps
  for each row execute function public.set_updated_at ();

-- ---------------------------------------------------------------------------
-- stamps.tour_id integrity : ensure the denormalized tour_id always matches
-- the spot's tour_id. Prevents a client from inserting a stamp with a tour_id
-- that differs from the spot's real tour (which would let RLS membership
-- checks be spoofed against the wrong tour).
-- ---------------------------------------------------------------------------
create or replace function public.sync_stamp_tour_id ()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select s.tour_id into new.tour_id
  from public.spots s
  where s.id = new.spot_id;
  if new.tour_id is null then
    raise exception 'spot % does not exist', new.spot_id;
  end if;
  return new;
end;
$$;

drop trigger if exists stamps_sync_tour_id on public.stamps;
create trigger stamps_sync_tour_id
  before insert or update of spot_id on public.stamps
  for each row execute function public.sync_stamp_tour_id ();

-- ---------------------------------------------------------------------------
-- @MX:ANCHOR: [AUTO] reorder_spots() renumbers a tour's spots atomically.
-- @MX:REASON: REQ-F5-007 / D11 / EC-12 require concurrent visit-order edits to
-- resolve to a single gap-free, duplicate-free sequence. Doing this as one
-- server-side transaction (rather than N client UPDATEs) is the invariant that
-- guarantees continuity under concurrent reorders.
--
-- @MX:WARN: [AUTO] Authorization is enforced INSIDE the function, not by RLS.
-- @MX:REASON: This is SECURITY DEFINER and bypasses RLS, so it must itself
-- check is_tour_member(); otherwise any caller could renumber any tour.
--
-- Contract:
--   p_tour_id     : the tour whose spots are being reordered.
--   p_ordered_ids : spot ids in the desired visit order. MUST be exactly the
--                   full set of the tour's spot ids (no missing, no extra).
-- Renumbers order_index to 1..N following the array order, in one statement.
-- ---------------------------------------------------------------------------
create or replace function public.reorder_spots (
  p_tour_id uuid,
  p_ordered_ids uuid[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count_actual integer;
  v_count_given  integer;
begin
  -- Caller must be a member of this tour (any member may reorder per
  -- REQ-F6-005; owner-only is not required for ordering).
  if not public.is_tour_member (p_tour_id) then
    raise exception 'not authorized to reorder spots for tour %', p_tour_id
      using errcode = '42501';
  end if;

  -- The provided id list must match the tour's spot set exactly, otherwise we
  -- would leave gaps / orphans. Reject mismatches rather than silently fixing.
  select count(*) into v_count_actual
  from public.spots
  where tour_id = p_tour_id;

  v_count_given := coalesce(array_length(p_ordered_ids, 1), 0);

  if v_count_given <> v_count_actual then
    raise exception
      'ordered id count (%) does not match tour spot count (%)',
      v_count_given, v_count_actual
      using errcode = '22023';
  end if;

  -- Single UPDATE: each spot gets its 1-based position in the array.
  -- with ordinality yields the array position used as the new order_index.
  update public.spots s
  set order_index = ord.position,
      updated_at  = now()
  from (
    select id, position
    from unnest(p_ordered_ids) with ordinality as t (id, position)
  ) ord
  where s.id = ord.id
    and s.tour_id = p_tour_id;

  -- Guard: every targeted id must have belonged to this tour. If any id was
  -- foreign, fewer rows updated than expected -> abort the transaction.
  get diagnostics v_count_given = row_count;
  if v_count_given <> v_count_actual then
    raise exception
      'one or more ids do not belong to tour %', p_tour_id
      using errcode = '22023';
  end if;
end;
$$;


-- ============================================================
-- 20260619000300_rls_policies.sql
-- ============================================================
-- =============================================================================
-- SPEC-BREADTOUR-001 :: Migration 3 / Row Level Security
-- Enable RLS on every table + explicit per-operation policies (NFR-SEC-004).
-- =============================================================================
-- THREAT MODEL (D10 / A13): the Supabase anon key is public and shipped in the
-- client bundle. Anyone can issue arbitrary PostgREST queries with it. Data
-- security depends ENTIRELY on the policies below. They are therefore written
-- default-deny: RLS is enabled on every table, and a row is only readable or
-- writable when a matching policy's USING / WITH CHECK clause returns true.
-- No table is left without explicit per-operation (SELECT/INSERT/UPDATE/DELETE)
-- coverage.
--
-- Depends on migration 1 (is_tour_member / is_tour_owner) and migration 2.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Enable RLS (default-deny once enabled and no policy matches).
-- FORCE so that even the table owner is subject to RLS via PostgREST.
-- ---------------------------------------------------------------------------
alter table public.profiles      enable row level security;
alter table public.tours         enable row level security;
alter table public.tour_members  enable row level security;
alter table public.tour_invites  enable row level security;
alter table public.spots         enable row level security;
alter table public.spot_menus    enable row level security;
alter table public.stamps        enable row level security;

-- Drop-then-create so the migration can be re-applied without "already exists".
-- =============================================================================
-- profiles
--   SELECT : a user may read their own profile and the profiles of anyone who
--            shares a tour with them (so member lists can show display names).
--   INSERT : a user may create only their own profile row (id = auth.uid()).
--            (Normally created by the on_auth_user_created trigger.)
--   UPDATE : a user may update only their own profile.
--   DELETE : no policy -> deletion only happens via auth.users cascade.
-- =============================================================================
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select to authenticated
  using (
    id = auth.uid ()
    or exists (
      select 1
      from public.tour_members me
      join public.tour_members them on them.tour_id = me.tour_id
      where me.user_id = auth.uid ()
        and them.user_id = public.profiles.id
    )
  );

drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles
  for insert to authenticated
  with check (id = auth.uid ());

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles
  for update to authenticated
  using (id = auth.uid ())
  with check (id = auth.uid ());

-- =============================================================================
-- tours
--   SELECT : members only (REQ-F5-006 / NFR-SEC-004 SELECT).
--   INSERT : any authenticated user may create a tour, but only as its own
--            owner (owner_id = auth.uid()). REQ-F6-001. The after-insert
--            trigger then adds the owner membership row.
--   UPDATE : owner only (e.g. rename). REQ-F6-004.
--   DELETE : owner only (REQ-F6-004 / REQ-F6-006). Cascades to all child rows.
-- =============================================================================
drop policy if exists tours_select on public.tours;
create policy tours_select on public.tours
  for select to authenticated
  using (public.is_tour_member (id));

drop policy if exists tours_insert on public.tours;
create policy tours_insert on public.tours
  for insert to authenticated
  with check (owner_id = auth.uid ());

drop policy if exists tours_update on public.tours;
create policy tours_update on public.tours
  for update to authenticated
  using (public.is_tour_owner (id))
  with check (public.is_tour_owner (id));

drop policy if exists tours_delete on public.tours;
create policy tours_delete on public.tours
  for delete to authenticated
  using (public.is_tour_owner (id));

-- =============================================================================
-- tour_members
--   SELECT : a user may see the membership rows of any tour they belong to
--            (to render the member list). Uses is_tour_member (SECURITY
--            DEFINER) to avoid RLS recursion on this same table.
--   INSERT : owner may add members; OR a user may add THEMSELVES as a member
--            (role 'member') -- this is how invite acceptance works
--            (REQ-F6-003). Self-insert as 'owner' is blocked.
--   UPDATE : owner only (e.g. role change). REQ-F6-004.
--   DELETE : owner may remove any member; a member may remove only themselves
--            (leave the tour). REQ-F6-004 / REQ-F6-006.
-- =============================================================================
drop policy if exists tour_members_select on public.tour_members;
create policy tour_members_select on public.tour_members
  for select to authenticated
  using (public.is_tour_member (tour_id));

drop policy if exists tour_members_insert on public.tour_members;
create policy tour_members_insert on public.tour_members
  for insert to authenticated
  with check (
    public.is_tour_owner (tour_id)
    or (user_id = auth.uid () and role = 'member')
  );

drop policy if exists tour_members_update on public.tour_members;
create policy tour_members_update on public.tour_members
  for update to authenticated
  using (public.is_tour_owner (tour_id))
  with check (public.is_tour_owner (tour_id));

drop policy if exists tour_members_delete on public.tour_members;
create policy tour_members_delete on public.tour_members
  for delete to authenticated
  using (
    public.is_tour_owner (tour_id)
    or user_id = auth.uid ()
  );

-- =============================================================================
-- tour_invites
--   SELECT : tour members may see their tour's invites; additionally an
--            invitee may see an invite addressed to their own email (so they
--            can view/accept it before joining). REQ-F6-002/003.
--   INSERT : owner (or any member -- "권한 있는 멤버", REQ-F6-002) may create
--            invites, and only as themselves (invited_by = auth.uid()).
--   UPDATE : the invitee may update status (accept/reject) on an invite for
--            their own email; the owner may also update (e.g. revoke).
--   DELETE : owner only (revoke an invite). REQ-F6-004.
-- =============================================================================
drop policy if exists tour_invites_select on public.tour_invites;
create policy tour_invites_select on public.tour_invites
  for select to authenticated
  using (
    public.is_tour_member (tour_id)
    or invited_email = (auth.jwt () ->> 'email')
  );

drop policy if exists tour_invites_insert on public.tour_invites;
create policy tour_invites_insert on public.tour_invites
  for insert to authenticated
  with check (
    public.is_tour_member (tour_id)
    and invited_by = auth.uid ()
  );

drop policy if exists tour_invites_update on public.tour_invites;
create policy tour_invites_update on public.tour_invites
  for update to authenticated
  using (
    public.is_tour_owner (tour_id)
    or invited_email = (auth.jwt () ->> 'email')
  )
  with check (
    public.is_tour_owner (tour_id)
    or invited_email = (auth.jwt () ->> 'email')
  );

drop policy if exists tour_invites_delete on public.tour_invites;
create policy tour_invites_delete on public.tour_invites
  for delete to authenticated
  using (public.is_tour_owner (tour_id));

-- =============================================================================
-- spots
--   SELECT : members only (NFR-SEC-004 SELECT).
--   INSERT : members may add spots (REQ-F6-005). Membership is checked on the
--            NEW row's tour_id.
--   UPDATE : members may edit spots (REQ-F6-005). Both the existing and the
--            new tour_id must be a tour the user belongs to (prevents moving a
--            spot into a tour they are not a member of).
--   DELETE : OWNER only (REQ-F6-004 / REQ-F6-006). Cascades to spot_menus and
--            stamps (REQ-F6-007 / D3).
-- =============================================================================
drop policy if exists spots_select on public.spots;
create policy spots_select on public.spots
  for select to authenticated
  using (public.is_tour_member (tour_id));

drop policy if exists spots_insert on public.spots;
create policy spots_insert on public.spots
  for insert to authenticated
  with check (public.is_tour_member (tour_id));

drop policy if exists spots_update on public.spots;
create policy spots_update on public.spots
  for update to authenticated
  using (public.is_tour_member (tour_id))
  with check (public.is_tour_member (tour_id));

drop policy if exists spots_delete on public.spots;
create policy spots_delete on public.spots
  for delete to authenticated
  using (public.is_tour_owner (tour_id));

-- =============================================================================
-- spot_menus
--   SELECT : members of the spot's tour (NFR-SEC-004 SELECT).
--   INSERT : members may add menus, only attributed to themselves
--            (author_id = auth.uid()). REQ-F4-001 / REQ-F6-005.
--   UPDATE : the menu's author may edit their own menu (members edit menus,
--            REQ-F6-005, scoped to authorship to avoid clobbering others).
--   DELETE : the menu's author, OR the tour owner, may delete a menu.
-- Membership is resolved through the parent spot's tour_id.
-- =============================================================================
drop policy if exists spot_menus_select on public.spot_menus;
create policy spot_menus_select on public.spot_menus
  for select to authenticated
  using (
    exists (
      select 1 from public.spots s
      where s.id = spot_menus.spot_id
        and public.is_tour_member (s.tour_id)
    )
  );

drop policy if exists spot_menus_insert on public.spot_menus;
create policy spot_menus_insert on public.spot_menus
  for insert to authenticated
  with check (
    author_id = auth.uid ()
    and exists (
      select 1 from public.spots s
      where s.id = spot_menus.spot_id
        and public.is_tour_member (s.tour_id)
    )
  );

drop policy if exists spot_menus_update on public.spot_menus;
create policy spot_menus_update on public.spot_menus
  for update to authenticated
  using (author_id = auth.uid ())
  with check (author_id = auth.uid ());

drop policy if exists spot_menus_delete on public.spot_menus;
create policy spot_menus_delete on public.spot_menus
  for delete to authenticated
  using (
    author_id = auth.uid ()
    or exists (
      select 1 from public.spots s
      where s.id = spot_menus.spot_id
        and public.is_tour_owner (s.tour_id)
    )
  );

-- =============================================================================
-- stamps
--   SELECT : members of the stamp's tour (NFR-SEC-004 SELECT).
--   INSERT : a member may insert ONLY their own stamp (user_id = auth.uid())
--            for a spot in a tour they belong to. REQ-F1-002 / NFR-SEC-004.
--   UPDATE : the stamp's own user OR the tour owner. This covers stamp
--            cancellation (setting cancelled_at) and arrival-time correction
--            (REQ-F1-009 / REQ-F1-010). Non-owners editing another member's
--            stamp are rejected (REQ-F1-010 / EC-11).
--   DELETE : the stamp's own user OR the tour owner (NFR-SEC-004 DELETE:
--            "stamps 취소는 본인 또는 소유자만"). Note: normal cancellation is a
--            soft-cancel UPDATE; hard DELETE is allowed for the same parties.
-- =============================================================================
drop policy if exists stamps_select on public.stamps;
create policy stamps_select on public.stamps
  for select to authenticated
  using (public.is_tour_member (tour_id));

drop policy if exists stamps_insert on public.stamps;
create policy stamps_insert on public.stamps
  for insert to authenticated
  with check (
    user_id = auth.uid ()
    and public.is_tour_member (tour_id)
  );

drop policy if exists stamps_update on public.stamps;
create policy stamps_update on public.stamps
  for update to authenticated
  using (
    user_id = auth.uid ()
    or public.is_tour_owner (tour_id)
  )
  with check (
    user_id = auth.uid ()
    or public.is_tour_owner (tour_id)
  );

drop policy if exists stamps_delete on public.stamps;
create policy stamps_delete on public.stamps
  for delete to authenticated
  using (
    user_id = auth.uid ()
    or public.is_tour_owner (tour_id)
  );


-- ============================================================
-- 20260619000400_realtime.sql
-- ============================================================
-- =============================================================================
-- SPEC-BREADTOUR-001 :: Migration 4 / Realtime publication
-- Add collaborative tables to supabase_realtime so row-level changes broadcast
-- to subscribed clients (REQ-F5-002, row-level last-write-wins per D4).
-- =============================================================================
-- Realtime broadcasts respect RLS: a subscriber only receives change events
-- for rows they are allowed to SELECT under the policies in migration 3.
--
-- We publish the tables that collaborative editing and the stamp board depend
-- on: tours (rename/delete), tour_members (joins/leaves), spots (add/edit/
-- reorder), spot_menus (menu edits), stamps (stamp board updates).
-- tour_invites is intentionally NOT published (invite flow does not need a
-- live channel for the MVP).
-- =============================================================================

-- supabase_realtime publication is created by the Supabase platform. On a bare
-- local Postgres it may not exist yet; create it defensively.
do $$
begin
  if not exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    create publication supabase_realtime;
  end if;
end $$;

-- Add tables idempotently. ALTER PUBLICATION ... ADD TABLE errors if the table
-- is already a member, so guard each one against pg_publication_tables.
do $$
declare
  t text;
  tbls text[] := array['tours', 'tour_members', 'spots', 'spot_menus', 'stamps'];
begin
  foreach t in array tbls loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- REPLICA IDENTITY FULL so UPDATE/DELETE realtime payloads include the full old
-- row. Without this, deletes broadcast only the primary key, which is enough to
-- remove a row from the UI but not to show "what changed" for last-write-wins
-- conflict toasts (NFR-CONFLICT-003).
alter table public.tours        replica identity full;
alter table public.tour_members replica identity full;
alter table public.spots        replica identity full;
alter table public.spot_menus   replica identity full;
alter table public.stamps       replica identity full;


-- ============================================================
-- 20260619000500_manual_checkin_requests.sql
-- ============================================================
-- =============================================================================
-- SPEC-BREADTOUR-001 :: Migration 5 / Manual check-in requests (REQ-F1-007)
-- Table: manual_checkin_requests
-- Plus the confirm_manual_checkin() RPC that atomically turns a peer-confirmed
-- request into a real stamp (AC-F1-04).
-- =============================================================================
-- WHY a separate table (not a pending state on stamps):
--   A row in `stamps` means a VALID arrival. AC-F1-04 says the stamp is only
--   applied AFTER a DIFFERENT member confirms a request. A pending row therefore
--   is NOT a stamp and must not appear in the stamp board, the partial-unique
--   re-stamp index, or stampMapBySpot. Keeping requests in their own table leaves
--   every stamp invariant from migration 2 untouched and gives a clean place to
--   enforce "requester != confirmer" (REQ-F1-007 / NFR-SEC-004).
--
-- THREAT MODEL (D10 / A13): the anon key is public; security is RLS-only. This
-- migration is written default-deny with explicit per-operation policies and a
-- SECURITY DEFINER confirm function that re-checks authorization itself.
--
-- Depends on migration 1 (tours / is_tour_member / is_tour_owner / set_updated_at)
-- and migration 2 (spots / stamps + the partial unique index + sync trigger).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Status enum for a manual check-in request lifecycle.
--   pending   : awaiting another member's confirmation.
--   confirmed : a different member confirmed -> a stamp was created.
--   cancelled : the requester (or owner) withdrew the request.
-- ---------------------------------------------------------------------------
do $$ begin
  create type manual_checkin_status as enum ('pending', 'confirmed', 'cancelled');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- manual_checkin_requests : a member's request to be stamped at a spot when GPS
-- auto-stamp is unavailable (REQ-F1-007). tour_id is denormalized (like stamps)
-- so RLS membership checks and the realtime filter run without a join; it is
-- kept consistent with the spot by sync_manual_checkin_tour_id() below.
--   - requester_id : the member who needs the stamp.
--   - confirmed_by : the DIFFERENT member who confirmed (null until confirmed).
--   - stamp_id     : the stamp produced on confirmation (null until confirmed).
-- We store NO raw coordinates (NFR-GEO-006 / A12); only the spot + member ids.
-- ---------------------------------------------------------------------------
create table if not exists public.manual_checkin_requests (
  id           uuid primary key default gen_random_uuid (),
  spot_id      uuid not null references public.spots (id) on delete cascade,
  tour_id      uuid not null references public.tours (id) on delete cascade,
  requester_id uuid not null references auth.users (id) on delete cascade,
  status       manual_checkin_status not null default 'pending',
  confirmed_by uuid references auth.users (id) on delete set null,
  stamp_id     uuid references public.stamps (id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  -- A request can never be self-confirmed at the data level (REQ-F1-007). This
  -- is a hard backstop in addition to the RLS / RPC checks.
  constraint manual_checkin_no_self_confirm
    check (confirmed_by is null or confirmed_by <> requester_id)
);

create index if not exists manual_checkin_tour_id_idx
  on public.manual_checkin_requests (tour_id);
create index if not exists manual_checkin_spot_id_idx
  on public.manual_checkin_requests (spot_id);
create index if not exists manual_checkin_requester_idx
  on public.manual_checkin_requests (requester_id);

-- @MX:ANCHOR: [AUTO] Partial unique index enforces "at most one PENDING request
-- per (spot, requester)" so a member cannot spam duplicate pending requests.
-- @MX:REASON: REQ-F1-007 — a member needs exactly one outstanding request per
-- spot; confirmed/cancelled rows (history) must NOT block a fresh request, so the
-- predicate is limited to status = 'pending' (mirrors the stamps re-stamp index).
create unique index if not exists manual_checkin_pending_unique
  on public.manual_checkin_requests (spot_id, requester_id)
  where status = 'pending';

drop trigger if exists manual_checkin_set_updated_at on public.manual_checkin_requests;
create trigger manual_checkin_set_updated_at
  before update on public.manual_checkin_requests
  for each row execute function public.set_updated_at ();

-- ---------------------------------------------------------------------------
-- Keep the denormalized tour_id consistent with the spot's real tour_id, so a
-- client cannot point a request at a tour they are not a member of (mirrors
-- sync_stamp_tour_id in migration 2).
-- ---------------------------------------------------------------------------
create or replace function public.sync_manual_checkin_tour_id ()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select s.tour_id into new.tour_id
  from public.spots s
  where s.id = new.spot_id;
  if new.tour_id is null then
    raise exception 'spot % does not exist', new.spot_id;
  end if;
  return new;
end;
$$;

drop trigger if exists manual_checkin_sync_tour_id on public.manual_checkin_requests;
create trigger manual_checkin_sync_tour_id
  before insert or update of spot_id on public.manual_checkin_requests
  for each row execute function public.sync_manual_checkin_tour_id ();

-- =============================================================================
-- RLS : default-deny, explicit per-operation (NFR-SEC-004).
-- =============================================================================
alter table public.manual_checkin_requests enable row level security;

-- SELECT : any member of the request's tour may see its requests, so another
--          member can find a pending request and confirm it (REQ-F1-007).
drop policy if exists manual_checkin_select on public.manual_checkin_requests;
create policy manual_checkin_select on public.manual_checkin_requests
  for select to authenticated
  using (public.is_tour_member (tour_id));

-- INSERT : a member may create ONLY their own request (requester_id = auth.uid())
--          for a spot in a tour they belong to. They cannot request on behalf of
--          someone else (REQ-F1-007 / NFR-SEC-004 INSERT).
drop policy if exists manual_checkin_insert on public.manual_checkin_requests;
create policy manual_checkin_insert on public.manual_checkin_requests
  for insert to authenticated
  with check (
    requester_id = auth.uid ()
    and status = 'pending'
    and public.is_tour_member (tour_id)
  );

-- UPDATE : the requester (to withdraw their own pending request) OR the tour
--          owner (moderation). NOTE: confirmation does NOT go through this policy
--          -- it goes through the SECURITY DEFINER RPC below, which enforces the
--          confirmer != requester rule. A direct UPDATE here can never set
--          confirmed_by to oneself because the CHECK constraint forbids self-
--          confirm and this policy only permits the requester/owner. So peer
--          confirmation must use the RPC. We still scope writes tightly.
drop policy if exists manual_checkin_update on public.manual_checkin_requests;
create policy manual_checkin_update on public.manual_checkin_requests
  for update to authenticated
  using (
    requester_id = auth.uid ()
    or public.is_tour_owner (tour_id)
  )
  with check (
    requester_id = auth.uid ()
    or public.is_tour_owner (tour_id)
  );

-- DELETE : the requester or the tour owner may delete a request row.
drop policy if exists manual_checkin_delete on public.manual_checkin_requests;
create policy manual_checkin_delete on public.manual_checkin_requests
  for delete to authenticated
  using (
    requester_id = auth.uid ()
    or public.is_tour_owner (tour_id)
  );

-- =============================================================================
-- @MX:ANCHOR: [AUTO] confirm_manual_checkin() is the ONLY path that turns a
-- pending request into a real stamp; it is the server-side guard for
-- "confirmed by a DIFFERENT member" (REQ-F1-007 / AC-F1-04).
-- @MX:REASON: AC-F1-04 requires the stamp to exist only after a peer confirms.
-- Doing the confirmer-check + stamp insert + request update as one SECURITY
-- DEFINER transaction is the invariant that prevents self-confirmation and
-- partial state; clients must never insert the stamp directly for a manual
-- check-in.
--
-- @MX:WARN: [AUTO] SECURITY DEFINER bypasses RLS, so every authorization rule is
-- enforced INSIDE this function.
-- @MX:REASON: the function runs as owner and could otherwise stamp any spot for
-- anyone; it must itself verify membership AND that the caller is not the
-- requester before inserting the stamp.
--
-- Contract:
--   p_request_id : the pending request to confirm.
--   Returns the created stamp id.
-- Behaviour:
--   - caller (auth.uid()) MUST be a member of the request's tour.
--   - caller MUST NOT be the requester (peer confirmation, REQ-F1-007).
--   - request MUST still be 'pending' (idempotency / no double-confirm).
--   - inserts a stamp (method 'manual', server arrived_at) for the REQUESTER;
--     the partial unique index from migration 2 still applies, so if the
--     requester already has a valid stamp this raises a unique violation
--     (REQ-F1-004). Re-stamp after cancel still works (cancelled_at IS NULL).
--   - marks the request confirmed and links the new stamp.
-- =============================================================================
create or replace function public.confirm_manual_checkin (
  p_request_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_req     public.manual_checkin_requests%rowtype;
  v_stamp_id uuid;
begin
  -- Lock the request row so two concurrent confirmers cannot both proceed.
  select * into v_req
  from public.manual_checkin_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'manual check-in request % not found', p_request_id
      using errcode = 'P0002';
  end if;

  if not public.is_tour_member (v_req.tour_id) then
    raise exception 'not authorized to confirm check-ins for this tour'
      using errcode = '42501';
  end if;

  -- Peer confirmation only: the confirmer must differ from the requester
  -- (REQ-F1-007 / AC-F1-04). This is the real server guard.
  if auth.uid () = v_req.requester_id then
    raise exception 'a manual check-in must be confirmed by another member'
      using errcode = '42501';
  end if;

  if v_req.status <> 'pending' then
    raise exception 'manual check-in request % is not pending', p_request_id
      using errcode = '22023';
  end if;

  -- Create the actual stamp for the REQUESTER. arrived_at is the server default
  -- (A6 / REQ-F1-003); the stamps.sync_stamp_tour_id + partial unique index
  -- still apply (REQ-F1-004 / REQ-F1-011).
  insert into public.stamps (spot_id, user_id, method)
  values (v_req.spot_id, v_req.requester_id, 'manual')
  returning id into v_stamp_id;

  update public.manual_checkin_requests
  set status       = 'confirmed',
      confirmed_by = auth.uid (),
      stamp_id     = v_stamp_id
  where id = p_request_id;

  return v_stamp_id;
end;
$$;

-- =============================================================================
-- Realtime : publish manual_checkin_requests so a pending request from one
-- member surfaces live to other members who can confirm it (REQ-F1-007 +
-- REQ-F5-002 live reflection). REPLICA IDENTITY FULL so UPDATE/DELETE payloads
-- carry the full row (needed to notify the requester on confirmation).
-- =============================================================================
do $$
begin
  if not exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    create publication supabase_realtime;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'manual_checkin_requests'
  ) then
    alter publication supabase_realtime
      add table public.manual_checkin_requests;
  end if;
end $$;

alter table public.manual_checkin_requests replica identity full;


-- ============================================================
-- 20260620000100_accept_invite_rpc.sql
-- ============================================================
-- =============================================================================
-- SPEC-BREADTOUR-001 :: Migration 6 / Atomic invite acceptance (REQ-F6-003)
-- accept_invite() RPC: validate a pending invite, insert the membership, and
-- mark the invite accepted in ONE transaction.
-- =============================================================================
-- WHY this RPC (defect H-02):
--   acceptInvite() previously did three separate client calls:
--     SELECT invite -> INSERT tour_members -> UPDATE invite status.
--   That sequence is NOT atomic. If the final UPDATE failed (network/RLS), the
--   user was left a member while the invite stayed 'pending' and therefore
--   reusable -- a duplicate-membership / replay hazard. Doing all three steps
--   inside a single SECURITY DEFINER function makes them one transaction: either
--   the membership AND the status change both commit, or neither does.
--
-- THREAT MODEL (D10 / A13): the anon key is public; security is RLS-only. This
-- function is SECURITY DEFINER (bypasses RLS) so it re-checks authorization
-- itself and pins search_path, mirroring confirm_manual_checkin() in migration 5
-- and reorder_spots() in migration 2.
--
-- Depends on migration 1 (tours / tour_members / tour_invites / tour_invite_status)
-- and migration 3 (tour_members_insert / tour_invites RLS policies).
-- =============================================================================

-- @MX:ANCHOR: [AUTO] accept_invite() is the ONLY atomic path that turns a
-- pending invite into a membership; membership insert + invite status update
-- happen in one transaction (REQ-F6-003 / AC-F6-03).
-- @MX:REASON: H-02 — the prior client-side SELECT->INSERT->UPDATE was non-atomic
-- and could leave a member attached to a still-reusable invite. This function is
-- the invariant that guarantees both writes commit together or not at all.
--
-- @MX:WARN: [AUTO] SECURITY DEFINER bypasses RLS, so authorization is enforced
-- INSIDE the function.
-- @MX:REASON: it runs as owner and could otherwise add anyone to any tour; it
-- must validate the invite is pending and bind the membership to auth.uid().
--
-- Contract:
--   p_token : the invite token being accepted.
--   Returns the tour id the caller just joined.
-- Behaviour:
--   - the invite MUST exist and still be 'pending' (no re-use of an
--     accepted/rejected invite -> raises, leaving no partial state).
--   - inserts a 'member' membership for the CALLER (auth.uid()); if they are
--     already a member the unique (tour_id, user_id) constraint short-circuits
--     to a no-op so acceptance stays idempotent.
--   - marks the invite 'accepted' so it cannot be replayed.
create or replace function public.accept_invite (
  p_token text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.tour_invites%rowtype;
begin
  if auth.uid () is null then
    raise exception 'authentication required to accept an invite'
      using errcode = '42501';
  end if;

  -- Lock the invite row so two concurrent acceptances cannot both proceed.
  select * into v_invite
  from public.tour_invites
  where token = p_token
  for update;

  if not found then
    raise exception 'invalid invite token'
      using errcode = 'P0002';
  end if;

  if v_invite.status <> 'pending' then
    raise exception 'invalid or already-used invite'
      using errcode = '22023';
  end if;

  -- Add the caller as a 'member'. Idempotent: an existing membership row for
  -- (tour, user) is left untouched rather than erroring, so a retried accept
  -- still ends in a consistent state.
  insert into public.tour_members (tour_id, user_id, role)
  values (v_invite.tour_id, auth.uid (), 'member')
  on conflict (tour_id, user_id) do nothing;

  -- Mark the invite accepted so it can never be reused (replay protection).
  update public.tour_invites
  set status = 'accepted'
  where id = v_invite.id;

  return v_invite.tour_id;
end;
$$;


-- ============================================================
-- 20260620000200_spot_menus_author_check.sql
-- ============================================================
-- =============================================================================
-- SPEC-BREADTOUR-001 :: Migration 7 / spot_menus author_id enforcement (M-02)
-- Harden the spot_menus INSERT path so the client can NEVER attribute a menu to
-- another member.
-- =============================================================================
-- WHY (defect M-02):
--   The anon key is public (D10 / A13); a client can POST any spot_menus row it
--   wants, including an arbitrary author_id. author_id drives the REQ-F4-003
--   authorship attribution AND the spot_menus UPDATE/DELETE policies (author may
--   edit/delete their own menu). If a client could forge author_id it could
--   impersonate another member or grant itself edit rights over a menu.
--
--   The INSERT policy from migration 3 already carries
--   `with check (author_id = auth.uid() and ...)`. This migration makes that
--   enforcement explicit, version-tracked, and re-asserts it idempotently
--   (drop-then-create) so the invariant cannot silently regress, and adds a
--   defence-in-depth note. RLS WITH CHECK is the enforcement mechanism here; a
--   table CHECK cannot reference auth.uid(), so the policy clause is the correct
--   server-side guard.
--
-- THREAT MODEL: security is RLS-only. This migration touches only the
-- spot_menus INSERT policy and is safe to re-apply.
--
-- Depends on migration 2 (spots / spot_menus) and migration 3 (is_tour_member
-- and the original spot_menus policies).
-- =============================================================================

-- @MX:ANCHOR: [AUTO] spot_menus_insert is the single guard that binds a new menu
-- to its real author; author_id MUST equal auth.uid() AND the author must be a
-- member of the menu's tour.
-- @MX:REASON: M-02 / REQ-F4-003 / NFR-SEC-004 — author_id is client-supplied and
-- drives authorship + the menu UPDATE/DELETE policies; without this WITH CHECK a
-- client could forge another member's author_id and impersonate them.
drop policy if exists spot_menus_insert on public.spot_menus;
create policy spot_menus_insert on public.spot_menus
  for insert to authenticated
  with check (
    -- The menu must be attributed to the caller themselves (no forging another
    -- member's author_id, M-02).
    author_id = auth.uid ()
    -- ...and the caller must belong to the spot's tour (REQ-F6-005).
    and exists (
      select 1 from public.spots s
      where s.id = spot_menus.spot_id
        and public.is_tour_member (s.tour_id)
    )
  );




-- =============================================================================
-- SPEC-BREADTOUR-001 :: Migration 7 / Fix tours SELECT owner-bootstrap (RLS)
-- Source file: supabase/migrations/20260620000300_fix_tours_select_owner.sql
-- Defect: tour creation via supabase-js .insert(...).select() (PostgREST
-- Prefer: return=representation) fails with 42501
-- "new row violates row-level security policy for table \"tours\"".
-- =============================================================================
-- ROOT CAUSE:
--   tours_select used `using (public.is_tour_member(id))`. is_tour_member() is
--   SECURITY DEFINER + STABLE and reads tour_members. On INSERT ... RETURNING
--   (PostgREST issues a single statement when return=representation), the
--   freshly-created owner membership row from the AFTER-INSERT trigger
--   add_owner_membership is NOT yet visible to the RETURNING clause's SELECT
--   policy evaluation. is_tour_member(id) therefore returns false and the
--   RETURNING row is rejected -> 42501.
--
-- FIX (minimal, security-preserving):
--   Allow the owner to read their own tour DIRECTLY via owner_id = auth.uid(),
--   OR'd with the existing membership check. Owner is always entitled to see
--   their tour (REQ-F6-001); non-members are still denied.
-- =============================================================================

drop policy if exists tours_select on public.tours;
create policy tours_select on public.tours
  for select to authenticated
  using (
    owner_id = auth.uid ()
    or public.is_tour_member (id)
  );
